# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 00:49
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=4, verbose_name='类别')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '类别',
                'verbose_name': '类别',
            },
        ),
        migrations.CreateModel(
            name='NoticeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='公告名称')),
                ('content', DjangoUeditor.models.UEditorField(default='', verbose_name='公告内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '版块公告',
                'verbose_name': '版块公告',
            },
        ),
        migrations.CreateModel(
            name='ReplyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_content', DjangoUeditor.models.UEditorField(default='', verbose_name='回复内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '回复内容',
                'verbose_name': '回复内容',
            },
        ),
        migrations.CreateModel(
            name='UserPostDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('content', DjangoUeditor.models.UEditorField(default='', verbose_name='帖子内容')),
                ('is_essence', models.BooleanField(default=False, verbose_name='是否为精华')),
                ('read_nums', models.IntegerField(default=0, verbose_name='阅读数')),
                ('reply_nums', models.IntegerField(default=0, verbose_name='回复数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_content.CategoryModel', verbose_name='类别')),
            ],
            options={
                'verbose_name_plural': '帖子内容',
                'verbose_name': '帖子内容',
            },
        ),
    ]
