# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 00:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum_content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userpostdetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='replymodel',
            name='reply_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='forum_content.UserPostDetail', verbose_name='回复对应文章'),
        ),
        migrations.AddField(
            model_name='replymodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
